---
# These strings are constants used by the dispatcher to select functionality at runtime
# Please implement all behaviour in the task-level dispatch.py file and then add the dispatch functions to the top-level dispatch.py
# Choose the model and dataset
model_and_data: CIFAR10_CNN  # CIFAR10_VIT
# Choose the train, test and server fed_eval functions
train_structure: CIFAR10

# Client fit config
fit_config:
  # Default net is empty and takes no args
  net_config: {}
  # Default dataloader is empty, added just for completeness
  dataloader_config:
    batch_size: 4
  # Train function needs epochs, other args TBC
  run_config:
    epochs: 3
    learning_rate: 0.01
  # no extra config (for now)
  extra: {}

# Client eval config
eval_config:
  net_config: {}
  # The batch size for testing can be as high as the GPU supports
  dataloader_config:
    batch_size: 8
  run_config: {}
  extra: {}

# Configuration for the federated testing function
# Follows the same conventions as the client config
fed_test_config:
  net_config: {}
  # Testing batch size can be as high as the GPU supports
  dataloader_config:
    batch_size: 4
  run_config: {}
  extra: {}

# Configuration instructions for initial parameter 
# generation
net_config_initial_parameters: {}

# The names of metrics you wish to aggregate
# E.g., train_loss, test_accuracy
fit_metrics: [train_loss, train_accuracy]
# TODO: 1. activations on uniformly distributed random samples
#       2. client activations on centralised test sets
#       3. client activations vs prev & current global model 
evaluate_metrics: [test_accuracy, test_confusion_matrix]
